{{- if or (eq (include "isProductionWithoutMasterKey" .) "true") (and (.Values.environment.MEILI_MASTER_KEY) (not .Values.auth.existingMasterKeySecret)) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "secretMasterKeyName" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secretMasterKeyName" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
data:
  {{- if $secret }}
  MEILI_MASTER_KEY: {{ $secret.data.MEILI_MASTER_KEY }}
  {{- else if (.Values.environment.MEILI_MASTER_KEY) }}
  MEILI_MASTER_KEY: {{ .Values.environment.MEILI_MASTER_KEY | b64enc }}
  {{ else }}
  MEILI_MASTER_KEY: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
{{ end }}
