{{- if eq (include "isProductionWithoutMasterKey" .) "true" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "secretMasterKeyName" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secretMasterKeyName" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
data:
  {{- if $secret }}
  MEILI_MASTER_KEY: {{ $secret.data.MEILI_MASTER_KEY }}
  {{ else }}
  MEILI_MASTER_KEY: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
{{ end }}
